# Generated by Django 4.0.4 on 2022-04-13 20:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='description',
            field=models.CharField(default='norms', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receiptfile',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
